In [72]:
#Nashville Housing Data - what is the best season for a single family to to sell a property?
import pandas as pd

In [73]:
#Unzip archive to Jupiter directory
path_to_zip_file = "nashville-housing-data.zip"
directory_to_extract_to = ""
import zipfile
zip_ref = zipfile.ZipFile(path_to_zip_file, 'r')
zip_ref.extractall(directory_to_extract_to)
zip_ref.close()

In [78]:
#Reading data in a csv file
df = pd.read_csv('Nashville_housing_data_2013_2016.csv')
df

,Unnamed: 0,Unnamed: 0.1,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,...,Building Value,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath
0,0,0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,...,134400.0,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0
2,2,2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,...,157800.0,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0
3,3,3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,...,243700.0,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0
4,4,4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,...,138100.0,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0
5,5,5,119 05 0 387.00,SINGLE FAMILY,2626 FOSTER AVE,NaN,NASHVILLE,2013-01-04,93736,20130118-0006110,...,86100.0,113300.0,1037.00000,CRAWL,1945.0,FRAME,C,2.0,1.0,0.0
6,6,6,119 10 0A 104.00,RESIDENTIAL CONDO,104 PRESCOTT PL,NaN,NASHVILLE,2013-01-07,64900,20130109-0002881,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,7,119 13 0 183.00,SINGLE FAMILY,501 MORTON AVE,NaN,NASHVILLE,2013-01-15,44000,20130115-0004888,...,68100.0,84300.0,1216.00000,CRAWL,1932.0,FRAME,D,2.0,1.0,0.0
8,8,8,119 13 0 183.00,SINGLE FAMILY,501 MORTON AVE,NaN,NASHVILLE,2013-01-25,49900,20130128-0008950,...,68100.0,84300.0,1216.00000,CRAWL,1932.0,FRAME,D,2.0,1.0,0.0
9,9,9,119 15 0 158.00,SINGLE FAMILY,113 NEESE DR,NaN,NASHVILLE,2013-01-09,25000,20130111-0003850,...,57100.0,88400.0,1152.00000,CRAWL,1945.0,FRAME,C,2.0,1.0,0.0
10,10,10,133 07 0 195.00,SINGLE FAMILY,184 WHEELER AVE,NaN,NASHVILLE,2013-01-18,90000,20130123-0007357,...,80100.0,105100.0,1300.00000,CRAWL,1955.0,BRICK,C,2.0,1.0,0.0
11,11,11,133 12 0 153.00,SINGLE FAMILY,238 ELYSIAN FIELDS RD,NaN,NASHVILLE,2013-01-11,72000,20130115-0004796,...,87900.0,109400.0,1175.00000,CRAWL,1968.0,BRICK,C,3.0,1.0,1.0
12,12,12,133 12 0 268.00,SINGLE FAMILY,3801 ECKHART DR,NaN,NASHVILLE,2013-01-04,120000,20130114-0004153,...,107800.0,129300.0,1825.00000,SLAB,1978.0,BRICK,C,7.0,2.0,0.0
13,13,13,133 14 0 084.00,VACANT RES LAND,4832 CORNING DR,NaN,NASHVILLE,2013-01-23,55000,20130129-0009135,...,201300.0,236800.0,1960.00000,CRAWL,2013.0,BRICK,C,4.0,2.0,1.0
14,14,14,134 13 0 004.00,SINGLE FAMILY,285 PARAGON MILLS RD,NaN,NASHVILLE,2013-01-18,115900,20130122-0006704,...,81700.0,103200.0,1474.00000,FULL BSMT,1960.0,BRICK,C,2.0,1.0,1.0
15,15,15,134 13 0 077.00,SINGLE FAMILY,259 EISENHOWER DR,NaN,NASHVILLE,2013-01-17,120000,20130122-0006935,...,92000.0,116300.0,1600.00000,SLAB,1962.0,BRICK,C,4.0,1.0,1.0
16,16,16,146 15 0 123.00,SINGLE FAMILY,5100 OVERTON RD,NaN,NASHVILLE,2013-01-04,262500,20130108-0002255,...,213600.0,269000.0,1436.00000,CRAWL,1955.0,BRICK,C,2.0,2.0,0.0
17,17,17,147 03 0B 089.00,RESIDENTIAL CONDO,370 WALLACE RD,C-10,NASHVILLE,2013-01-29,31416,20130129-0009357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,18,147 12 0A 109.00,RESIDENTIAL CONDO,109 NORTHCREST COMMONS CIR,NaN,NASHVILLE,2013-01-16,127500,20130117-0005497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,19,148 01 0 188.00,DUPLEX,281 COMROE RD,NaN,NASHVILLE,2013-01-31,112500,20130131-0010288,...,71100.0,99100.0,1436.00000,CRAWL,1970.0,BRICK,C,4.0,2.0,0.0
20,20,20,148 10 0 051.00,SINGLE FAMILY,3922 CREEKSIDE DR,NaN,NASHVILLE,2013-01-08,134000,20130114-0004339,...,83100.0,104300.0,1455.00000,CRAWL,1958.0,BRICK,C,3.0,2.0,0.0
21,21,21,148 14 0 004.00,SINGLE FAMILY,4907 PACKARD DR,NaN,NASHVILLE,2013-01-18,48000,20130123-0007489,...,53400.0,74400.0,950.00000,CRAWL,1958.0,BRICK,C,2.0,1.0,0.0
22,22,22,148 14 0 062.00,SINGLE FAMILY,3805 CREEKSIDE DR,NaN,NASHVILLE,2013-01-22,127000,20130123-0007382,...,107100.0,128100.0,1927.00000,CRAWL,1959.0,BRICK,C,4.0,2.0,0.0
23,23,23,148 15 0 231.00,SINGLE FAMILY,225 CLIPPER CT,NaN,NASHVILLE,2013-01-08,92900,20130122-0006732,...,66600.0,81600.0,1293.00000,CRAWL,1980.0,FRAME,C,4.0,1.0,1.0
24,24,24,160 03 0 127.00,SINGLE FAMILY,5316 OVERTON RD,NaN,NASHVILLE,2013-01-04,267300,20130108-0002110,...,300400.0,355400.0,2370.00000,FULL BSMT,1968.0,BRICK,B,4.0,2.0,0.0
25,25,25,160 11 0A 088.00,SINGLE FAMILY,5510 HEARTHSTONE LN,NaN,BRENTWOOD,2013-01-15,270000,20130117-0005616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,26,160 16 0B 019.00,SINGLE FAMILY,6144 BRENTWOOD CHASE DR,NaN,BRENTWOOD,2013-01-25,295000,20130128-0008669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,27,161 02 0 005.00,SINGLE FAMILY,641 MCMURRAY DR,NaN,NASHVILLE,2013-01-28,187000,20130131-0010008,...,151300.0,187800.0,2010.00000,CRAWL,1965.0,BRICK,C,3.0,2.0,0.0
28,28,28,161 10 0A 139.00,SINGLE FAMILY,5229 CARDIFF DR,NaN,NASHVILLE,2013-01-25,137000,20130131-0010232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,29,161 10 0B 164.00,SINGLE FAMILY,4717 CHEPSTOW DR,NaN,NASHVILLE,2013-01-25,216000,20130128-0008655,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56606,56606,56606,176 05 0A 020.00,SINGLE FAMILY,6724 BIRCHBROOK DR,NaN,ANTIOCH,2016-10-31,178000,20161109-0118794,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56607,56607,56607,176 09 0 003.00,SINGLE FAMILY,4964 HICKORY WOODS E,NaN,ANTIOCH,2016-10-28,236000,20161031-0114817,...,159300.0,184300.0,3117.00000,SLAB,1995.0,BRICK/FRAME,C,3.0,3.0,0.0
56608,56608,56608,081 12 0B 134.00,RESIDENTIAL CONDO,1400 ROSA L PARKS BLVD,134.0,NASHVILLE,2016-10-26,490000,20161027-0113564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56609,56609,56609,081 12 0B 222.00,RESIDENTIAL CONDO,1400 ROSA L PARKS BLVD,222.0,NASHVILLE,2016-10-25,232500,20161031-0115115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56610,56610,56610,081 12 0K 001.00,RESIDENTIAL CONDO,1514 AARTHUR AVE,NaN,NASHVILLE,2016-10-24,454900,20161101-0115200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56611,56611,56611,081 12 0T 450.00,RESIDENTIAL CONDO,1350 ROSA L PARKS BLVD,450.0,NASHVILLE,2016-10-28,275000,20161031-0114658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56612,56612,56612,081 16 0 197.00,VACANT RESIDENTIAL LAND,1017 MONROE ST,NaN,NASHVILLE,2016-10-24,231500,20161026-0113388,...,0.0,40000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56613,56613,56613,081 16 0J 002.00,RESIDENTIAL CONDO,1405 BARTHUR AVE,NaN,NASHVILLE,2016-10-14,425000,20161014-0109043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56614,56614,56614,082 05 0 040.00,SINGLE FAMILY,1625 5TH AVE N,NaN,NASHVILLE,2016-10-28,466000,20161102-0115988,...,204100.0,256000.0,1637.00000,CRAWL,2004.0,FRAME,B,3.0,2.0,1.0
56615,56615,56615,082 05 0 058.00,SINGLE FAMILY,1614 5TH AVE N,NaN,NASHVILLE,2016-10-26,685000,20161101-0115366,...,295900.0,351600.0,2478.00000,CRAWL,2005.0,FRAME,B,4.0,3.0,1.0
56616,56616,56616,082 05 0 098.00,VACANT RESIDENTIAL LAND,1709 3RD AVE N,NaN,NASHVILLE,2016-10-12,280000,20161017-0109149,...,5100.0,46000.0,1180.00000,CRAWL,1899.0,BRICK,D,3.0,1.0,0.0
56617,56617,56617,082 05 0Y 001.00,VACANT RESIDENTIAL LAND,1707 3RD AVE N,NaN,NASHVILLE,2016-10-12,280000,20161017-0109149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56618,56618,56618,082 05 0Y 002.00,VACANT RESIDENTIAL LAND,1709 3RD AVE N,NaN,NASHVILLE,2016-10-12,280000,20161017-0109149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56619,56619,56619,082 09 0J 300.00,RESIDENTIAL CONDO,300 VAN BUREN ST,NaN,NASHVILLE,2016-10-11,395000,20161014-0108728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56620,56620,56620,082 09 0J 507.00,RESIDENTIAL CONDO,428 VAN BUREN ST,NaN,NASHVILLE,2016-10-19,1050000,20161021-0111505,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56621,56621,56621,082 09 0P 103.00,CONDOMINIUM OFC OR OTHER COM CONDO,500 MADISON ST,103.0,NASHVILLE,2016-10-04,232000,20161006-0105768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56622,56622,56622,082 13 0E 137.00,RESIDENTIAL CONDO,827 3RD AVE N,NaN,NASHVILLE,2016-10-14,455000,20161017-0109543,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56623,56623,56623,082 13 0G 206.00,RESIDENTIAL CONDO,303 CRIDDLE ST,206.0,NASHVILLE,2016-10-21,266000,20161025-0112743,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56624,56624,56624,082 14 0A 144.00,RESIDENTIAL CONDO,732 1ST AVE N,NaN,NASHVILLE,2016-10-04,227900,20161005-0105373,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56625,56625,56625,093 05 2B 014.00,RESIDENTIAL CONDO,700 CHURCH ST,306.0,NASHVILLE,2016-10-07,228600,20161012-0107848,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56626,56626,56626,093 06 0A 004.00,RESIDENTIAL CONDO,301 DEMONBREUN ST,201.0,NASHVILLE,2016-10-20,325000,20161027-0113759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56627,56627,56627,093 09 0C 090.00,RESIDENTIAL CONDO,1212 LAUREL ST,1003.0,NASHVILLE,2016-10-21,589900,20161114-0119528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56628,56628,56628,093 09 0C 105.00,RESIDENTIAL CONDO,1212 LAUREL ST,1103.0,NASHVILLE,2016-10-11,543000,20161014-0108683,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56629,56629,56629,093 09 0C 262.00,RESIDENTIAL CONDO,1212 LAUREL ST,2110.0,NASHVILLE,2016-10-03,397000,20161006-0105844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56630,56630,56630,093 11 0B 012.00,RESIDENTIAL CONDO,464 2ND AVE S,NaN,NASHVILLE,2016-10-14,275000,20161018-0109872,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56631,56631,56631,093 13 0B 274.00,RESIDENTIAL CONDO,320 11TH AVE S,274.0,NASHVILLE,2016-10-06,210000,20161007-0106599,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56632,56632,56632,093 13 0D 044.00,RESIDENTIAL CONDO,700 12TH AVE S,608.0,NASHVILLE,2016-10-25,338000,20161101-0115186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56633,56633,56633,093 13 0D 048.00,RESIDENTIAL CONDO,700 12TH AVE S,613.0,NASHVILLE,2016-10-04,742000,20161010-0106889,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56634,56634,56634,093 13 0D 056.00,RESIDENTIAL CONDO,700 12TH AVE S,708.0,NASHVILLE,2016-10-26,320000,20161031-0114730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56635,56635,56635,093 13 0D 094.00,RESIDENTIAL CONDO,700 12TH AVE S,1008.0,NASHVILLE,2016-10-27,330000,20161104-0117077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
df.describe()

,Unnamed: 0,Unnamed: 0.1,Sale Price,Acreage,Neighborhood,Land Value,Building Value,Total Value,Finished Area,Year Built,Bedrooms,Full Bath,Half Bath
count,56636.00000,56636.00000,5.663600e+04,26017.000000,26017.000000,2.601700e+04,2.601700e+04,2.601700e+04,24166.000000,24165.000000,24159.000000,24277.000000,24146.000000
mean,28317.50000,28317.50000,3.272111e+05,0.498903,4356.215782,6.907267e+04,1.608025e+05,2.323971e+05,1926.954345,1963.749224,3.090029,1.886106,0.283981
std,16349.54926,16349.54926,9.287425e+05,1.570396,2170.348270,1.060405e+05,2.068041e+05,2.810703e+05,1687.017313,26.546141,0.852942,0.961572,0.487905
min,0.00000,0.00000,5.000000e+01,0.010000,107.000000,1.000000e+02,0.000000e+00,1.000000e+02,0.000000,1799.000000,0.000000,0.000000,0.000000
25%,14158.75000,14158.75000,1.350000e+05,0.180000,3126.000000,2.100000e+04,7.590000e+04,1.028000e+05,1239.000000,1948.000000,3.000000,1.000000,0.000000
50%,28317.50000,28317.50000,2.054500e+05,0.270000,3929.000000,2.880000e+04,1.114000e+05,1.485000e+05,1632.000000,1960.000000,3.000000,2.000000,0.000000
75%,42476.25000,42476.25000,3.290000e+05,0.450000,6228.000000,6.000000e+04,1.807000e+05,2.685000e+05,2212.000000,1983.000000,3.000000,2.000000,1.000000
max,56635.00000,56635.00000,5.427806e+07,160.060000,9530.000000,2.772000e+06,1.297180e+07,1.394040e+07,197988.000000,2017.000000,11.000000,10.000000,3.000000

In [80]:
#Dropping 2 first columns as they don't have relevant data
df = df.drop('Unnamed: 0', axis=1)
df = df.drop("Unnamed: 0.1", axis=1)
df.head()

,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,...,Building Value,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath
0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,No,No,...,134400.0,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0
2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,No,No,...,157800.0,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0
3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,No,No,...,243700.0,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0
4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,No,No,...,138100.0,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0

In [81]:
#Creating function to extract month from Sales Date
#vals=1 as Month is on second place in data 2013-01-24 (year = 0, month=1, date=2). 
#If we need to get year of sale, vals equals to 0, etc.
import numpy as np

def getMonth(x) :
    vals = x.split("-")
    return vals[1]
df['Sale Month'] = df['Sale Date'].apply(getMonth)
df.head()

,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,...,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath,Sale Month
0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01
1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,No,No,...,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0,01
2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,No,No,...,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0,01
3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,No,No,...,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0,01
4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,No,No,...,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0,01

In [83]:
#Creating function to convert Month into a season
def getSeason(x):
    if x=="12":
        return "Winter"
    if x=="01":
        return "Winter"
    if x=="02":
        return "Winter"
    if x=="03":
        return "Spring"
    if x=="04":
        return "Spring"
    if x=="05":
        return "Spring"
    if x=="06":
        return "Summer"
    if x=="07":
        return "Summer"
    if x=="08":
        return "Summer"
    if x=="09":
        return "Fall"
    if x=="10":
        return "Fall"
    if x=="11":
        return "Fall"
df['Sale Season'] = df['Sale Month'].apply(getSeason)
df.head()

,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,...,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath,Sale Month,Sale Season
0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,Winter
1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,No,No,...,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0,01,Winter
2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,No,No,...,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0,01,Winter
3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,No,No,...,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0,01,Winter
4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,No,No,...,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0,01,Winter

In [84]:
pd.pivot_table(df, index=['Sale Season'])

,Acreage,Bedrooms,Building Value,Finished Area,Full Bath,Half Bath,Land Value,Neighborhood,Sale Price,Total Value,Year Built
Sale Season,,,,,,,,,,,
Fall,0.486353,3.068972,156665.094492,1891.911539,1.858179,0.280680,65934.945889,4333.560976,302914.733363,225130.762397,1964.195346
Spring,0.462048,3.102935,159611.384487,1910.413376,1.899955,0.276018,68742.597581,4296.528635,289425.441804,230749.228107,1963.393164
Summer,0.543102,3.103471,166850.302938,1979.740554,1.895347,0.295597,72802.538556,4431.753244,313081.953268,242350.491432,1963.419764
Winter,0.494810,3.073733,157389.668310,1904.727676,1.885728,0.279893,67128.930749,4345.571268,446523.105693,226911.068803,1964.309818

In [89]:
pd.pivot_table(df, index=['Land Use','Sale Season'])

                                                      Acreage  Bedrooms  \
Land Use                               Sale Season
APARTMENT: LOW RISE (BUILT SINCE 1960) Spring        1.170000  0.000000
CHURCH                                 Fall          1.088750  1.400000
                                       Spring        1.070000  1.000000
                                       Summer        4.620000  0.666667
                                       Winter        1.914000  1.285714
CLUB/UNION HALL/LODGE                  Summer        0.220000  0.000000
CONDO                                  Fall               NaN       NaN
                                       Spring             NaN       NaN
                                       Summer             NaN       NaN
                                       Winter             NaN       NaN
CONDOMINIUM OFC  OR OTHER COM CONDO    Fall               NaN       NaN
                                       Spring             NaN       NaN
                                       Summer             NaN       NaN
                                       Winter             NaN       NaN
CONVENIENCE MARKET WITHOUT GAS         Summer        0.380000  0.000000
DAY CARE CENTER                        Fall          0.590000  3.000000
                                       Spring        2.660000  0.000000
DORMITORY/BOARDING HOUSE               Fall          0.232500  4.500000
                                       Spring        0.210000  4.000000
                                       Summer        0.332857  4.000000
                                       Winter        0.617500  5.000000
DUPLEX                                 Fall          0.338143  3.898113
                                       Spring        0.332918  3.948795
                                       Summer        0.309809  3.764205
                                       Winter        0.316772  3.925311
FOREST                                 Fall         14.910000  4.000000
                                       Spring       16.645000  3.000000
                                       Summer       26.107500  2.000000
GREENBELT                              Fall         10.390000  4.000000
                                       Spring       39.335000       NaN
...                                                       ...       ...
SINGLE FAMILY                          Winter        0.460114  3.021776
SMALL SERVICE SHOP                     Summer             NaN       NaN
SPLIT CLASS                            Fall          3.312000  3.750000
                                       Spring        7.760000  7.000000
                                       Summer        2.848000  3.250000
                                       Winter        4.822500  4.250000
STRIP SHOPPING CENTER                  Spring        0.120000  0.000000
TERMINAL/DISTRIBUTION WAREHOUSE        Summer        0.680000  0.000000
TRIPLEX                                Fall          0.277619  4.900000
                                       Spring        0.215714  4.782609
                                       Summer        0.195556  5.111111
                                       Winter        0.228824  5.062500
VACANT COMMERCIAL LAND                 Spring        0.200000       NaN
                                       Summer        0.150000       NaN
VACANT RES LAND                        Fall          0.862353  3.432432
                                       Spring        0.674536  3.402062
                                       Summer        1.604865  3.564103
                                       Winter        0.756239  3.559322
VACANT RESIDENTIAL LAND                Fall          0.900815  3.261364
                                       Spring        0.685788  3.400000
                                       Summer        1.266803  3.610390
                                       Winter        1.094466  3.288136
VACANT RESIENTIAL LAND                 Fall          1.150000       NaN
                                       Spring        0.805000       NaN
VACANT RURAL LAND                      Summer        8.505000       NaN
VACANT ZONED MULTI FAMILY              Winter        0.455000       NaN
ZERO LOT LINE                          Fall          0.153727  2.327273
                                       Spring        0.160597  2.407960
                                       Summer        0.160139  2.386760
                                       Winter        0.173577  2.423358

                                                    Building Value  \
Land Use                               Sale Season
APARTMENT: LOW RISE (BUILT SINCE 1960) Spring         4.189000e+05
CHURCH                                 Fall           3.348750e+05
                                       Spring         1.047000e+05
                                       Summer         1.774362e+06
                                       Winter         2.480300e+05
CLUB/UNION HALL/LODGE                  Summer         3.110000e+04
CONDO                                  Fall                    NaN
                                       Spring                  NaN
                                       Summer                  NaN
                                       Winter                  NaN
CONDOMINIUM OFC  OR OTHER COM CONDO    Fall                    NaN
                                       Spring                  NaN
                                       Summer                  NaN
                                       Winter                  NaN
CONVENIENCE MARKET WITHOUT GAS         Summer         9.500000e+03
DAY CARE CENTER                        Fall           2.035000e+05
                                       Spring         6.376000e+05
DORMITORY/BOARDING HOUSE               Fall           1.649000e+05
                                       Spring         1.133000e+05
                                       Summer         2.254429e+05
                                       Winter         1.145000e+05
DUPLEX                                 Fall           1.099875e+05
                                       Spring         1.149618e+05
                                       Summer         1.045519e+05
                                       Winter         1.037776e+05
FOREST                                 Fall           2.400000e+03
                                       Spring         1.267500e+04
                                       Summer         8.850000e+03
GREENBELT                              Fall           2.505000e+04
                                       Spring         0.000000e+00
...                                                            ...
SINGLE FAMILY                          Winter         1.671817e+05
SMALL SERVICE SHOP                     Summer                  NaN
SPLIT CLASS                            Fall           1.641600e+05
                                       Spring         6.014000e+05
                                       Summer         3.858400e+05
                                       Winter         2.934250e+05
STRIP SHOPPING CENTER                  Spring         2.872000e+05
TERMINAL/DISTRIBUTION WAREHOUSE        Summer         2.170000e+04
TRIPLEX                                Fall           9.404286e+04
                                       Spring         7.638571e+04
                                       Summer         1.019222e+05
                                       Winter         1.390941e+05
VACANT COMMERCIAL LAND                 Spring         0.000000e+00
                                       Summer         0.000000e+00
VACANT RES LAND                        Fall           1.853647e+05
                                       Spring         1.869072e+05
                                       Summer         2.103905e+05
                                       Winter         1.993110e+05
VACANT RESIDENTIAL LAND                Fall           7.924944e+04
                                       Spring         6.004863e+04
                                       Summer         7.782558e+04
                                       Winter         8.726893e+04
VACANT RESIENTIAL LAND                 Fall           0.000000e+00
                                       Spring         0.000000e+00
VACANT RURAL LAND                      Summer         0.000000e+00
VACANT ZONED MULTI FAMILY              Winter         0.000000e+00
ZERO LOT LINE                          Fall           6.854955e+04
                                       Spring         7.151294e+04
                                       Summer         7.168780e+04
                                       Winter         7.182482e+04

                                                    Finished Area  Full Bath  \
Land Use                               Sale Season
APARTMENT: LOW RISE (BUILT SINCE 1960) Spring        14157.000000   0.000000
CHURCH                                 Fall           6959.125000   0.375000
                                       Spring         2863.000000   0.666667
                                       Summer        28601.500000   0.500000
                                       Winter         4498.732001   0.900000
CLUB/UNION HALL/LODGE                  Summer         2333.000000   0.000000
CONDO                                  Fall                   NaN        NaN
                                       Spring                 NaN        NaN
                                       Summer                 NaN        NaN
                                       Winter                 NaN        NaN
CONDOMINIUM OFC  OR OTHER COM CONDO    Fall                   NaN        NaN
                                       Spring                 NaN        NaN
                                       Summer                 NaN        NaN
                                       Winter                 NaN        NaN
CONVENIENCE MARKET WITHOUT GAS         Summer         1640.000000   0.000000
DAY CARE CENTER                        Fall           2900.000000   3.000000
                                       Spring         3570.000000   0.000000
DORMITORY/BOARDING HOUSE               Fall           2313.750000   2.250000
                                       Spring         1747.500000   2.000000
                                       Summer         2291.678576   2.428571
                                       Winter         2834.200010   2.500000
DUPLEX                                 Fall           1988.776773   2.384906
                                       Spring         2010.832327   2.436747
                                       Summer         1879.266506   2.343750
                                       Winter         1884.385229   2.377593
FOREST                                 Fall           1545.000000   1.000000
                                       Spring         1296.000000   2.000000
                                       Summer         1396.000000   2.000000
GREENBELT                              Fall           1796.000000   1.000000
                                       Spring                 NaN        NaN
...                                                           ...        ...
SINGLE FAMILY                          Winter         1884.225431   1.847013
SMALL SERVICE SHOP                     Summer                 NaN        NaN
SPLIT CLASS                            Fall           2823.625000   2.500000
                                       Spring         9170.000000   6.000000
                                       Summer         6424.009995   1.500000
                                       Winter         3611.669998   3.000000
STRIP SHOPPING CENTER                  Spring         3214.000000   0.000000
TERMINAL/DISTRIBUTION WAREHOUSE        Summer         4031.000000   0.000000
TRIPLEX                                Fall           2155.026996   3.000000
                                       Spring         2173.626959   2.956522
                                       Summer         2207.005554   3.166667
                                       Winter         2468.158119   3.062500
VACANT COMMERCIAL LAND                 Spring                 NaN        NaN
                                       Summer                 NaN        NaN
VACANT RES LAND                        Fall           2738.054594   2.414634
                                       Spring         2655.439949   2.359223
                                       Summer         2890.597124   2.476190
                                       Winter         2855.470595   2.622951
VACANT RESIDENTIAL LAND                Fall           2688.484432   1.982301
                                       Spring         2736.235469   1.984848
                                       Summer         3223.915584   2.111111
                                       Winter         2578.037588   1.924051
VACANT RESIENTIAL LAND                 Fall                   NaN        NaN
                                       Spring                 NaN        NaN
VACANT RURAL LAND                      Summer                 NaN        NaN
VACANT ZONED MULTI FAMILY              Winter                 NaN        NaN
ZERO LOT LINE                          Fall           1213.441795   1.490909
                                       Spring         1250.212811   1.666667
                                       Summer         1253.794460   1.620209
                                       Winter         1275.222263   1.554745

                                                    Half Bath     Land Value  \
Land Use                               Sale Season
APARTMENT: LOW RISE (BUILT SINCE 1960) Spring        0.000000   70500.000000
CHURCH                                 Fall          0.125000   82500.000000
                                       Spring        0.000000   99300.000000
                                       Summer        0.000000   88125.000000
                                       Winter        0.200000  128050.000000
CLUB/UNION HALL/LODGE                  Summer        0.000000   18000.000000
CONDO                                  Fall               NaN            NaN
                                       Spring             NaN            NaN
                                       Summer             NaN            NaN
                                       Winter             NaN            NaN
CONDOMINIUM OFC  OR OTHER COM CONDO    Fall               NaN            NaN
                                       Spring             NaN            NaN
                                       Summer             NaN            NaN
                                       Winter             NaN            NaN
CONVENIENCE MARKET WITHOUT GAS         Summer        0.000000   26000.000000
DAY CARE CENTER                        Fall          0.000000   47000.000000
                                       Spring        0.000000     100.000000
DORMITORY/BOARDING HOUSE               Fall          0.250000   41550.000000
                                       Spring        0.000000   33600.000000
                                       Summer        0.285714   40857.142857
                                       Winter        0.500000   48000.000000
DUPLEX                                 Fall          0.113636   59697.500000
                                       Spring        0.127660   59239.660057
                                       Summer        0.082857   59866.120219
                                       Winter        0.112033   52690.944882
FOREST                                 Fall          0.000000   31923.000000
                                       Spring        0.000000   15156.750000
                                       Summer        0.000000  717465.250000
GREENBELT                              Fall          0.000000   26321.000000
                                       Spring             NaN   85710.000000
...                                                       ...            ...
SINGLE FAMILY                          Winter        0.270430   69328.804666
SMALL SERVICE SHOP                     Summer             NaN            NaN
SPLIT CLASS                            Fall          0.750000  123520.000000
                                       Spring        0.000000  170700.000000
                                       Summer        0.750000  164680.000000
                                       Winter        0.500000  120125.000000
STRIP SHOPPING CENTER                  Spring        0.000000  100000.000000
TERMINAL/DISTRIBUTION WAREHOUSE        Summer        0.000000   11000.000000
TRIPLEX                                Fall          0.000000   77938.095238
                                       Spring        0.000000   44982.142857
                                       Summer        0.055556   62450.000000
                                       Winter        0.125000   42429.411765
VACANT COMMERCIAL LAND                 Spring             NaN   33750.000000
                                       Summer             NaN   20860.000000
VACANT RES LAND                        Fall          0.634146   92172.058824
                                       Spring        0.683168   68097.938144
                                       Summer        0.642857   92001.351351
                                       Winter        0.716667   76355.045872
VACANT RESIDENTIAL LAND                Fall          0.533981   63900.000000
                                       Spring        0.524590   73738.356164
                                       Summer        0.638889   76010.741688
                                       Winter        0.552632   64706.985437
VACANT RESIENTIAL LAND                 Fall               NaN  240000.000000
                                       Spring             NaN  137500.000000
VACANT RURAL LAND                      Summer             NaN   91000.000000
VACANT ZONED MULTI FAMILY              Winter             NaN   23350.000000
ZERO LOT LINE                          Fall          0.522727   20479.545455
                                       Spring        0.388060   24456.716418
                                       Summer        0.418118   25327.874564
                                       Winter        0.489051   27748.905109

                                                    Neighborhood  \
Land Use                               Sale Season
APARTMENT: LOW RISE (BUILT SINCE 1960) Spring         326.000000
CHURCH                                 Fall          3340.750000
                                       Spring        4493.166667
                                       Summer        2351.125000
                                       Winter        4784.800000
CLUB/UNION HALL/LODGE                  Summer        6950.000000
CONDO                                  Fall                  NaN
                                       Spring                NaN
                                       Summer                NaN
                                       Winter                NaN
CONDOMINIUM OFC  OR OTHER COM CONDO    Fall                  NaN
                                       Spring                NaN
                                       Summer                NaN
                                       Winter                NaN
CONVENIENCE MARKET WITHOUT GAS         Summer        4830.000000
DAY CARE CENTER                        Fall          7328.000000
                                       Spring        3211.000000
DORMITORY/BOARDING HOUSE               Fall          4553.000000
                                       Spring        3628.000000
                                       Summer        3113.285714
                                       Winter        3628.500000
DUPLEX                                 Fall          3913.639286
                                       Spring        4041.971671